### ISSUE TITLE
CSS selectors with multiple rules redeclared in media queries results in multiple blocks

### ISSUE THREAD

**Issue by runar** [MadLittleMods/postcss-css-variables#109]
I believe this issue is related to both #64 and #67, but it’s not quite the same as no duplication is involved.

If a CSS selector has multiple rules that are redeclared by the same media query, multiple media queries will be outputted with only one rule each. Take a look at the following example from the playground:

Input:

```css
:root {
  --background: #fff;
  --color: #000;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #000;
    --color: #fff;
  }
}

body {
  background-color: var(--background);
  color: var(--color);
}
```

Expected:

```css
body {
  background-color: #fff;
  color: #000;
}

@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: #fff;
  }
}
```

Actual output:

```css
body {
  background-color: #fff;
  color: #000;
}

@media (prefers-color-scheme: dark) {

  body {
  color: #fff;
  }
}

@media (prefers-color-scheme: dark) {

  body {
  background-color: #000;
  }
}
```

(Also notice how the rule order is reversed, indention is wrong, and an empty line is added below the media queries.)
