### ISSUE TITLE
Do not duplicate blocks of multiple comma separated selectors

### ISSUE THREAD

**Issue by SuperPat45** [MadLittleMods/postcss-css-variables#110]
Input:

```css
:root {
  --font-size: 12px;
  --font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
html,body {
  font-family: var(--font-family);
  font-size: var(--font-size);
}
```

Actual output:
```css
:root {
  --font-size: 12px;
  --font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
html {
  font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-family: var(--font-family);
  font-size: 12px;
  font-size: var(--font-size);
}
body {
  font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-family: var(--font-family);
  font-size: 12px;
  font-size: var(--font-size);
}
```

Expected:
```css
:root {
  --font-size: 12px;
  --font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
html,body {
  font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-family: var(--font-family);
  font-size: 12px;
  font-size: var(--font-size);
}
```
