### ISSUE TITLE
Two fallbacks after preprocessing 

### ISSUE THREAD

**Issue by DZakh** [MadLittleMods/postcss-css-variables#113]
Honestly I don't really know either it's an issue of postcss-css-variables or something else, but I'm going to keep it right here.
## My problem:
After I build my project I have two fallbacks for a css variable.
```css
:root {
  --main-clr: red;
}
/* Original code */
.some-selector {
  color: var(--main-clr);
}
/* Becomes */
.some-selector {
  color: red;
  color: red;
  color: var(--main-clr);
}
```
## And I've found how to fix it (after two hours)
I had to make postcss.config.js
```js
module.exports = {
  plugins: [require('postcss-preset-env')({})]
};
```
instead of .postcssrc
```
{
  "modules": true,
  "plugins": {
    "postcss-preset-env": {}
  }
}
```
## About my doubts
As I said before, it may be not a problem of the package, but some other things I use in my project:
Parcel, PostCss, my stupidity, or even Sass's imports.
