### ISSUE TITLE
Parenthesis problem

### ISSUE THREAD

**Issue by Mangatt** [MadLittleMods/postcss-css-variables#114]
When using rgba fallbacks for CSS variables, output is wrong:

```css
:root{
    --color: rgba(0,0,0,0.5);
}
p{
    color: var(--color, rgba(0,0,0,0.5));
}
```

is transformed into (notice two parentheses on the right):

```css
p{
    color: rgba(0,0,0,0.5));
}
```

Any way around that?
