### ISSUE TITLE
Preserve: "true" only returns fallback declaration

### ISSUE THREAD

**Issue by dippas** [MadLittleMods/postcss-css-variables#115]
Hi, I'm using `postcss-css-variables` in a gulp environment and whenever I set `preserve: "true"` it only returns the fallback declaration

Here is a simplified version of the gulpfile:

```js
const {src, dest, series, parallel, watch} = require('gulp'),
    concat = require('gulp-concat'),
    rename = require('gulp-rename'),
    sourcemaps = require('gulp-sourcemaps'),
    plumber = require('gulp-plumber'),
    sass = require('gulp-sass'),
    cleanCSS = require('gulp-clean-css'),
    autoprefixer = require('autoprefixer'),
    postCSS = require('gulp-postcss'),
    cssVars = require('postcss-css-variables'),
    gap = require('postcss-gap-properties')

function coreStyles(basename, source, dist) {
  src(source)
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(sass({
         outputStyle: 'expanded'
     }).on('error', sass.logError))
    .pipe(cleanCSS()) //minify
    .pipe(postCSS([gap(), 
        cssVars({
          preserve: 'true'
      }), autoprefixer({
          grid: 'autoplace'
    })]))
    .pipe(concat(`${basename}.css`))
    .pipe(rename({
    basename: basename,
        suffix: '.min'
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(dest(dist))
}

function styles(done) {
    coreStyles(
        'filename',
        sourceFolder
        distFolder
    )    
    done()
}

const dev = series(clean, parallel(styles, otherNotRelevantTasksHere))
exports.build = dev
exports.default = series(dev, otherNotRelevantTasksHere)
```

---
 Example:

```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(var(--spacing) * 5);
}

```

Expected output:

```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(1rem * 5);
  padding: calc(var(--spacing) * 5);
}

```
Actual output: 

```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(1rem * 5);
}

```

Can you tell what I am doing wrong here or is it a bug with gulp environment?

**Comment by MadLittleMods** [comment]
@dippas If I run your example through the [playground](https://madlittlemods.github.io/postcss-css-variables/playground/) with the `preserve` option on, it works as expected. It looks like one of your other plugins is messing with the output

You can try disabling your other plugins/pipes until you find what is stripping it out.

**Comment by dippas** [comment]
@MadLittleMods  thanks for replying, 

I've tried narrowing down the plugins/pipes for this use case, but no lucky, I'm inclined to say this could be an issue either with the `gulp-sass` (the compiler from SCSS to CSS), or some incompatibility with `postcss-css-vars` and `gulp` environment.

Here is the narrowed example I've come up with:

```js

const {src, dest} = require('gulp'),
    sass = require('gulp-sass'),
    postCSS = require('gulp-postcss'),
    cssVars = require('postcss-css-variables')

function styles(done) {
    src(paths.styles.app)
        .pipe(sass({
            outputStyle: 'expanded',
        }).on('error', sass.logError))
        .pipe(postCSS([
            cssVars({
                preserve: 'true'
            })
        ]))
        .pipe(dest(paths.styles.dist))
    done()
}

const dev = series(clean, parallel(styles, otherNotRelevantTasksHere))
exports.build = dev
exports.default = series(dev, otherNotRelevantTasksHere)

**Comment by MadLittleMods** [comment]
@dippas Please post the output from just the `sass` pipe (comment out the `postcss` stuff). That way, we can see your exact input that goes into `postcss-css-variables`. If necessary, reduce the Sass test case to reproduce as well.

**Comment by dippas** [comment]
@MadLittleMods  thanks for taking time in replying to me.

Here is the minimal input of `SCSS` with only `sass` pipe

```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(var(--spacing) * 5);
}
```
and the output is exactly the same in the `CSS` file:
```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(var(--spacing) * 5);
}
```

**Comment by MadLittleMods** [comment]
@dippas Thanks for the minimal example 👍

Looking at your config again you should write the option with quotes around the true value -> `preserve: true`. I'm not sure if that solves your problem since a string is still a truthy value.

```js
cssVars({
  preserve: true
})
```

---

In the playground with the `options.preserve = true`, https://madlittlemods.github.io/postcss-css-variables/playground/, everything looks expected 👀. Not sure what is going wrong in your setup

Input:

```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(var(--spacing) * 5);
}
```

Output (looks as expected ✔️ ):

```css
:root {
  --spacing: 1rem;
}

section {
  padding: calc(1rem * 5);
  padding: calc(var(--spacing) * 5);
}
```
