### ISSUE TITLE
Scoping issue on multiple class attributes - `undefined`

### ISSUE THREAD

**Issue by WolfgangKluge** [MadLittleMods/postcss-css-variables#12]
I am using `postcss-nested` and `postcss-css-variables` plugins in the [order as mentioned](https://github.com/MadLittleMods/postcss-css-variables#nested-rules).

I don't know which plugin is to blame, but if I have something like:

```css
.test {
    --a: 10px;
    &.sub {
        width: var(--a);
    }
}
```

I get:

```css
.test.sub {
    width: undefined;
}
```

If I add whitespace between `&` and `.sub`, it works as expected (apart from the fact it's no multiple class attribute anymore \*g\*). Even if I switch the order of the plugins, it works (but I've no idea what will not work then)...
