### ISSUE TITLE
Negative variables are not compiled after update

### ISSUE THREAD

**Issue by sn3p** [MadLittleMods/postcss-css-variables#122]
Did something change regarding the compilation of negative variables?

In v0.14.0 this:

```css
.foo {
  --width: 100px;
  with: -var(--width);
}
```

used to output :

```css
.foo {
  with: -100px;
}
```

But after updating to v0.17.0 I get:

```css
.foo {
  with: -var(--width);
}
```
