### ISSUE TITLE
Incorrect pseudo-selector output

### ISSUE THREAD

**Issue by siilike** [MadLittleMods/postcss-css-variables#125]
Input:
```
:root
{
	--XXX: 15px;
}

#test li
{
	font-size: var(--XXX);
}

#test:not(.class)
{
	--XXX: 8px;
}

#test2 li
{
	font-size: var(--XXX);
}

#test2:hover
{
	--XXX: 8px;
}
```
Expected:
```
#test li
{
	font-size: 15px;
}

#test:not(.class) li
{
	font-size: 8px;
}

#test2 li
{
	font-size: 15px;
}

#test2:hover li
{
	font-size: 8px;
}
```
Actual:
```
#test li
{
	font-size: 15px;
}

#test li:not(.class)
{
	font-size: 8px;
}

#test2 li
{
	font-size: 15px;
}

#test2 li:hover
{
	font-size: 8px;
}
```

**Comment by Ajith-stark** [comment]
same applies for pseduo-class
input : 
```css
.classname:focus{
  --bg-opacity: 1;
  background-color: rgba(183, 148, 244, var(--bg-opacity));
}
```

output: 
```css
.classname:focus{
  background-color: undefined;
}
.classname:focus:focus {
  background-color: rgba(183, 148, 244, 1);
}
```

expected : 
```css
.classname:focus {
  background-color: rgba(183, 148, 244, 1);
}
```
