### ISSUE TITLE
Nesting edge case: custom variable is not getting replaced

### ISSUE THREAD

**Issue by ajayjaggi97** [MadLittleMods/postcss-css-variables#130]
My postcss pipeline includes "postcss-nested" plugin before "postcss-css-variables" plugin.

You can see that in the output,  var(--ON-IMAGE) is not replaced.

**Input CSS**

```css
.translucentHoverBG {
  &:hover,
  &:focus {
    background: var(--TRANSLUCENT-HOVER-BG);
    span,
    i {
      color: var(--ON-IMAGE);
    }
  }
}
```

Output CSS
```css
.translucentHoverBG:hover {
    background: rgba(255, 255, 255, 0.3);
  }

.translucentHoverBG:hover span, .translucentHoverBG:hover i {
      color: var(--ON-IMAGE);
    }

.translucentHoverBG:focus {
    background: rgba(255, 255, 255, 0.3);
  }

.translucentHoverBG:focus span, .translucentHoverBG:focus i {
      color: var(--ON-IMAGE);
    }

```

**Comment by MadLittleMods** [comment]
Where is `--ON-IMAGE` defined?

---

It seems to work fine in my testing below:

Input:
```css
:root {
  --TRANSLUCENT-HOVER-BG: blue;
  --ON-IMAGE: red;
}

.translucentHoverBG {
  &:hover,
  &:focus {
    background: var(--TRANSLUCENT-HOVER-BG);
    span,
    i {
      color: var(--ON-IMAGE);
    }
  }
}
```


After `postcss-nested` (tested at https://sneakertack.github.io/postcss-playground/):

```css
:root {
  --TRANSLUCENT-HOVER-BG: blue;
  --ON-IMAGE: red;
}

.translucentHoverBG:hover, .translucentHoverBG:focus {
  background: var(--TRANSLUCENT-HOVER-BG)
}
.translucentHoverBG:hover span, .translucentHoverBG:hover i, .translucentHoverBG:focus span, .translucentHoverBG:focus i {
  color: var(--ON-IMAGE);
}
```

After `postcss-css-variables`, seems to work ✅:

```css
.translucentHoverBG:hover {
  background: blue
}

.translucentHoverBG:focus {
  background: blue
}
.translucentHoverBG:hover span {
  color: red;
}
.translucentHoverBG:hover i {
  color: red;
}
.translucentHoverBG:focus span {
  color: red;
}
.translucentHoverBG:focus i {
  color: red;
}
```

**Comment by ajayjaggi97** [comment]
Thanks for the quick reply @MadLittleMods.
I am passing the  values through the variables options. It doesn't seem to work for me.

**Comment by MadLittleMods** [comment]
Please provide the exact input before it's passed to `postcss-css-variables`. Also share the code you're using to run `postcss` and the plugins.

**Comment by ajayjaggi97** [comment]
I an using postcss-loader in webpack for postcss.

**postcss.config.js**

```
const path = require('path');
const { parseFilesSync } = require('./tools/css-variables-parser');

const variables = parseFilesSync([
  path.resolve(__dirname, 'node_modules', 'tailwindcss', 'dist', 'base.css'),
  path.resolve(__dirname, 'node_modules', 'tailwindcss', 'dist', 'utilities.css'),
  path.resolve(__dirname, 'src', 'styles', 'themes', '_default.css'),
  path.resolve(__dirname, 'src', 'styles', 'themes', '_tv.css'),
  path.resolve(__dirname, 'src', 'styles', '_custom-variables-default.css'),
  path.resolve(__dirname, 'src', 'styles', '_custom-variables-tv.css')
]);

let plugins = [
  require('postcss-prepend-imports')({
      path: path.resolve(__dirname, 'src', 'styles'),
      files: ['_custom-variables-overrides.css']
    }),
  require('postcss-import')({
    root: path.resolve(__dirname, 'src'),
    plugins: [require('stylelint')]
  }),
  require('postcss-reporter')({
    clearReportedMessages: true,
    throwError: true
  }),
  require('postcss-aspect-ratio-polyfill'),
  require('postcss-nested'),
  require('postcss-sassy-mixins'),
  require('tailwindcss'),
  require('postcss-extend-rule'),

  /*
   * Note:
   * rtlcss plugin generates separate css files for rtl styles.
   * But we need to figure out a way of dynamically consuming the css files based on the dir attribute inside storybook as well as consumer applications.
   * Hence using postcss-rtlcss for now.
   */
  require('postcss-rtlcss'),
  require('postcss-css-variables')({ variables, preserveInjectedVariables: false }),
  require('cssnano')({
    preset: 'default'
  }),
  require('autoprefixer')
];

plugins = plugins.filter((plugin) => !!plugin);

module.exports = {
  plugins
};
```

**Comment by MadLittleMods** [comment]
@ajayjaggi97 Testing the "CSS passed to postcss-css-variables plugin" works just fine in the playground, https://madlittlemods.github.io/postcss-css-variables/playground/

```css
:root {
  --TRANSLUCENT-HOVER-BG: blue;
  --ON-IMAGE: red;
}

.translucentHoverBG:hover,
  .translucentHoverBG:focus {
    background: var(--TRANSLUCENT-HOVER-BG);
  }

.translucentHoverBG:hover span, .translucentHoverBG:hover i, .translucentHoverBG:focus span, .translucentHoverBG:focus i {
      color: var(--ON-IMAGE);
    }
```

What does `console.log(variables)` show? I suspect something might not be as expected there or another plugin is messing with it.
