### ISSUE TITLE
postcss-css-variables: variable --color-text-5 is undefined and used without a fallback

### ISSUE THREAD

**Issue by cjy816618** [MadLittleMods/postcss-css-variables#133]
`"postcss-css-variables": "^0.17.0",`
 
Input:
```css
:root {
  --color-text-5: red;
}
div {
  color: var(--color-text-5);
}
```

Output: 
```css
div {
  color: undefined;
}
```

Expected output:
```css
div {
  color: red;
}
```

**Comment by MadLittleMods** [comment]
@cjy816618 Please provide your CSS input, what this plugin outputs, and what you expected the output to look like

**Comment by cjy816618** [comment]
css：
![image](https://user-images.githubusercontent.com/47617771/198486596-dbe998ac-f2d2-4cae-985b-ba2936a716e9.png)
plgin:
![image](https://user-images.githubusercontent.com/47617771/198486907-60604b5d-0e5a-4880-b4a0-dc37f2e95e76.png)
package:
![image](https://user-images.githubusercontent.com/47617771/198487272-cd4bd7e5-632e-46cc-8c1a-c072e5c6fe9e.png)
output：
![image](https://user-images.githubusercontent.com/47617771/198487853-80d56e41-4ff8-4882-a50e-5774f6178729.png)
I hope to be compatible with ie, I used this plugin, but it doesn't work in ie11

**Comment by MadLittleMods** [comment]
@cjy816618 Please update the issue description with a copy-pastable text version of minimal reproduction case

**Comment by cjy816618** [comment]
input:
:root{
--color-text-5:red;
}
div{
color:var(--color-text-5);
}
output: 
div{
color:undefined;
}
expected outpu:
div{
color:red;
}

**Comment by MadLittleMods** [comment]
I can't reproduce in the [code playground](https://madlittlemods.github.io/postcss-css-variables/playground/),

Input:
```css
:root {
  --color-text-5: red;
}
div {
  color: var(--color-text-5);
}
```

Output looks as your expected result:
```css
div {
  color: red;
}
```
