### ISSUE TITLE
Escaped Class Names Using Vars Incorrectly Set to `undefined`

### ISSUE THREAD

**Issue by shellscape** [MadLittleMods/postcss-css-variables#137]
Consider the following CSS:

```css
.bg-\\[url\\(https\\:\\/\\/example\\.com\\/image\\.png\\)\\] {
  --un-url: url(https://example.com/image.png); background-image:var(--un-url);
}
```

The output from running the plugin is:

```css
.bg-\\[url\\(https\\:\\/\\/example\\.com\\/image\\.png\\)\\] {
  background-image:undefined;
}
.bg-\\[url\\(https\\:\\/\\/example\\.com\\/image\\.png\\)\\]:\\/\\/example\\.com\\/image\\.png\\)\\]{
  background-image:url(https://example.com/image.png);
}
```

The plugin seems to have an issue with escaping, or a variable directly following escaping.
