### ISSUE TITLE
output css includes undefined

### ISSUE THREAD

**Issue by lovetingyuan** [MadLittleMods/postcss-css-variables#140]
![image](https://github.com/MadLittleMods/postcss-css-variables/assets/7310471/8c37c8df-0c59-49ab-9ad6-45575a1a36e5)

css input:
```css
.dark\:border-gray-100 {
  --tw-border-opacity: 1;
  border-color: rgb(243 244 246 / var(--tw-border-opacity));
}

```

output:
```css
.dark\:border-gray-100 {
  border-color: undefined;
}
.dark\:border-gray-100:border-gray-100 {
  border-color: rgb(243 244 246 / 1);
}

```

**Comment by joelmackenzie-lavvi** [comment]
I'm also seeing `undefined` when variables are set to other variables: 
Input:
```css
:root {
  --bs-emphasis-color: #000;
}

.table {
  --bs-table-color: var(--bs-emphasis-color);
  color: var(--bs-table-color);
}

.table>:not(caption) {
  --test-color: #fff;
  color: var(--bs-table-color);
  border-color: var(--test-color, #555);
}
```

Output: 
```css
:root {
  --bs-emphasis-color: #000;
}

.table {
  --bs-table-color: #000;    /* variable is set to the correct value */ 
  color: #000;
}

.table>:not(caption) {
  --test-color: #fff;
  color: undefined;   /* I expected this to be set to `#000`  */
  border-color: #555;    /* I expected this to be set to `#fff`  */
}

.table>:not(caption):not(caption) {     /*  Also, not sure why this was added.  */
  border-color: #fff;
}
```
