### ISSUE TITLE
Groups of CSS selectors are expand into separate, identical rules

### ISSUE THREAD

**Issue by heathflohre** [MadLittleMods/postcss-css-variables#141]
Currently, groups of selectors to have a variable to resolve are expanded into separate, identical css rules.

```css
:root {--color-foreground: #000000;}
p, h1 {color: var(--color-foreground);}
```

will expand to

```css
p {color: #000000;}
h1 {color: #000000;}
```

instead of

```css
p, h1 {color: #000000;}
```

Is this intended or a bug that can be fixed?
