### ISSUE TITLE
Duplicate rules created when @media rules are expanded

### ISSUE THREAD

**Issue by heathflohre** [MadLittleMods/postcss-css-variables#142]
```css
:root {--border: red;}
.hr td {background-color: var(--border);}
@media (prefers-color-scheme: dark) {
:root {--border: blue;}
.hr td {background-color: var(--border);}
}
```

currently expands to

```css
.hr td {background-color: red;}
@media (prefers-color-scheme: dark) {
.hr td {background-color: blue;}}
@media (prefers-color-scheme: dark) {
.hr td {background-color: blue;}
@media (prefers-color-scheme: dark) {
.hr td {background-color: blue;}}
}
```

Notice the duplicate @media rules?

**Comment by MadLittleMods** [comment]
For your input source CSS, it only needs to change the variable value in the media query:

Input:
```css
:root { --border: red; }
.hr td { background-color: var(--border); }

@media (prefers-color-scheme: dark) {
    :root { --border: blue; }
}
```

Output:
```css
.hr td { background-color: red; }

@media (prefers-color-scheme: dark) {
     .hr td { background-color: blue; }
}
```

But otherwise, "The output CSS is equivalent and while it could be compressed back down, I'd rather leave it as is. This could change after the refactor." ([*source*](https://github.com/MadLittleMods/postcss-css-variables/issues/28#issuecomment-175008515))
