### ISSUE TITLE
Dependent property redefinition

### ISSUE THREAD

**Issue by bangseongbeom** [MadLittleMods/postcss-css-variables#16]
Dependent property should be redefined if source property is changed.

Input:
```css
.a {
    --source: red;
    --dependent: var(--source);
	
    color: var(--dependent);
}

.a .b {
    --source: blue;

    color: var(--dependent);
}
```
---
Real:
```css
.a {
    color: red;
}

.a .b {
    color: red;
}
```
Expected:
```css
.a {
    color: red;
}

.a .b {
    color: blue;
}
```

**Comment by MadLittleMods** [comment]
Thank you for the bug report @bangseongbeom :grinning:

**Comment by Dangoo** [comment]
Any news on this issue?

There's also another issue when overwriting a variable more then one time:

```css
:root {
	--test: 300px;
	--bla: var(--test);
}

div {
	width: var(--test);
}

div.foo {
	--test: 200px;
	width: var(--bla);
}

div.bar {
	--test: 100px;
	width: var(--bla);
}
```
____

Actual:
```css
div {
	width: 100px;
}

div.foo {
	width: 100px;
}

div.bar {
	width: 100px;
}
````

Expected:

```css
div {
	width: 300px;
}

div.foo {
	width: 200px;
}

div.bar {
	width: 100px;
}
```
