### ISSUE TITLE
Not working when variables file is @import -ed

### ISSUE THREAD

**Issue by radubrehar** [MadLittleMods/postcss-css-variables#18]
I have variables in one file, let's call it `'vars.css'`

In `'main.css'` I try to `@import './vars.css'`and use variables. This fails and renders undefined. If I define variables in the same file where I use them, it's working.

**vars.css**
```css
:root {
  --red: #D85743;
}

```
**main.css**
```css
@import './vars.css'; /*or @import url('./vars.css')*/

.red {
  color: var(--red);
}
```
