### ISSUE TITLE
very cool, but incorrect while overriding

### ISSUE THREAD

**Issue by tunnckoCore** [MadLittleMods/postcss-css-variables#2]
At first.. lib is awesome!

**But** I think following output for that fixture isn't correct.

```css
:root {
    --some-width: 150px;
}

.box-foo {
    --some-width: 333px;
    width: var(--some-width);

    .box-bar {
        width: var(--some-width);
    }
}

@media (max-width: 800px) {
    .box-foo {
        --some-width: 300px;
    }
}
```
output
```css
.box-foo {
    width: 333px;

    .box-bar {
        width: 333px;
    }

    @media (max-width: 800px) {

        .box-bar {
            width: 300px;
        }
    }
}

@media (max-width: 800px) {

    .box-foo {
        width: 300px;
    }
}
```
notice the `.box-bar` in media query. I think it should be 333px;

**Comment by tunnckoCore** [comment]
Orrr if we accept that is correct, so it also should be 300px in box-bar outside the media query.

**Comment by tunnckoCore** [comment]
but yea, there have something wrong

```css
:root {
    --some-width: 150px;
}

.box-foo {
    --some-width: 333px;
    width: var(--some-width);

    .box-bar {
        width: var(--some-width);
    }
}

.box-baz {
    --some-width: 200px;
    width: var(--some-width);
}

@media (max-width: 800px) {
    .box-baz {
        --some-width: 550px;
    }
}
```
outputs

```css
.box-foo {
    width: 333px;

    .box-bar {
        width: 333px;
    }

    @media (max-width: 800px) {

        .box-bar {
            width: 550px;
        }
    }
}

@media (max-width: 800px) {

    .box-foo {
        width: 550px;
    }
}

.box-baz {
    width: 200px;
}

@media (max-width: 800px) {

    .box-baz {
        width: 550px;
    }
}
```
