### ISSUE TITLE
"/" character seems to break the line

### ISSUE THREAD

**Issue by metaloha** [MadLittleMods/postcss-css-variables#23]
For example, on line 133 of sanitize.css (currently), the following line appears:

    font: var(--html-font-size, 100%)/var(--html-line-height, 1.5) var(--font-family, sans-serif);

The postcss-custom-properties plugin correctly resolves this to read:

    font: 100% / 1.5 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif';

This plugin simply outputs:

    font: 100%;

**Comment by MadLittleMods** [comment]
Thank you for bug report @metaloha 

It seems to have to do with providing the fallbacks. You can try out the following snippet on the [playground](https://madlittlemods.github.io/postcss-css-variables/playground/) which works just fine

```css
.foo {
	--font-size: 14px;
	--line-height: 16px;

	font: var(--font-size)/var(--line-height) sans-serif;
}
```
