### ISSUE TITLE
Allow whitespace within var function

### ISSUE THREAD

**Issue by colinmeinke** [MadLittleMods/postcss-css-variables#27]
Input:

``` css
:root { --foo: red; }
.bar { color: var( --foo ); }
```

Expected output:

``` css
.bar { color: red; }
```

Actual output:

``` css
.bar { color: var( --foo ); }
```
