### ISSUE TITLE
Not completely normal work in the group selector

### ISSUE THREAD

**Issue by fsy0718** [MadLittleMods/postcss-css-variables#28]
```
:root{--color: red};
.test1,.test2{color: var(--color)};
```
this plugin output:
```
.test1{color: red;}
.test2{color: red}
```
but the `postcss-custom-properties` output:
```
.test1,.test2{color:red;}
```

**Comment by MadLittleMods** [comment]
The output CSS is equivalent and while it could be compressed back down, I'd rather leave it as is. This could change after the refactor.

Consider the following on why we do split it out always:

```css
.foo {
  --some-color: #f00;
}
.bar {
  --some-color: #0f0;
}

.foo, .bar {
  color: var(--some-color);
}
```
