### ISSUE TITLE
Don't suppress code when you don't know how to do with values

### ISSUE THREAD

**Issue by MoOx** [MadLittleMods/postcss-css-variables#3]
Input

```css
.title {
   background: var(--bg);
}
h1 {
  --bg: green;
}
h2 {
  --bg: red;
}
```
Output
```css
.title {
   background: undefined;
}
```

Definitly looks like a bug

**Comment by tunnckoCore** [comment]
:+1:

**Comment by MadLittleMods** [comment]
This is actually how I intended, because the variable was undefined at that scope. **We only work on explicitly defined scope.** I understand that with real CSS variables, the true cascade if you did `h1.title` or `h1 title` would resolve the value.

If you want to preserve the `var(...)` version of the background declaration, set the [`opts.preserve`](https://github.com/MadLittleMods/postcss-css-variables#preserve-default-false) option to `true`.

**Comment by tunnckoCore** [comment]
@MadLittleMods btw, add possibility to enable/disable options in the live playground.

```css
.title {
    background: url('./img/foobar.png');
    background: var(--bg);
}
```
output
```css
.title {
    background: url('./img/foobar.png');
    background: undefined;
}
```
not cool. what about to just save the old value of the property? and it will remain just `var(--bg);` and leave browser to decide how and what to do.
