### ISSUE TITLE
Bug: breaks "linear-gradient" value list

### ISSUE THREAD

**Issue by tlindig** [MadLittleMods/postcss-css-variables#35]
following results in unexpected code:

```
textarea {
  background-image: linear-gradient(var(--primary-color, #ff5722), var(--primary-color, #ffff22));
}

```

results in:

```
textarea {
  background-image: linear-gradient(#ff5722), var(--primary-color, #ffff22);
}

```

but should:

```
textarea {
  background-image: linear-gradient(#ff5722, #ffff22);
}
```

tested also with [playground](https://madlittlemods.github.io/postcss-css-variables/playground/)

**Comment by MadLittleMods** [comment]
:+1: Thanks for the report. It looks like the fallbacks are messing with things. 

For now you can work around it like this:

```css
.foo {
	--gradient-color1: var(--primary-color, #ff5722);
	--gradient-color2: var(--primary-color, #ffff22);
	background-image: linear-gradient(var(--gradient-color1), var(--gradient-color2));
}
```
