### ISSUE TITLE
Resolve nested `var` in fallback

### ISSUE THREAD

**Issue by asvny** [MadLittleMods/postcss-css-variables#37]
Just a spec clarification , are we allowed to refer fallback as another var ie `var(--color-2)`  from root

``` css
:root {
 --color-1:red;
 --color-2:green;
}

.Component {
  background: var(--color-10,var(--color-2))
}
```

I expect output to be 

``` css
.Component {
  background: green
}
```

but the current output is

``` css
.Component {
  background: var(--color-2)
}
```
