### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by annamalai-saro** [MadLittleMods/postcss-css-variables#40]
<img width="1434" alt="screen shot 2016-07-08 at 5 17 33 pm" src="https://cloud.githubusercontent.com/assets/5235065/16686485/19203a66-4530-11e6-9917-efb402d2ede4.png">

I hope the expected output is

```css
.c {
 position: relative;
}

.c:focus {
  border-color: blue
}

.c.is-error:focus{
  border-color:red
}
```
