### ISSUE TITLE
Option 'preserve' doesn't work inside @media rules

### ISSUE THREAD

**Issue by muftiev** [MadLittleMods/postcss-css-variables#42]
input css with option preserve = true
```css
@media screen and (max-width: 700px) {
    :root {
        --color-link: purple;
    }
}
.link {
    color: var(--color-link);
}
```

output
```css
@media screen and (max-width: 700px) {
    .link {
        color: purple;
    }
}
```

Expected output
```css
@media screen and (max-width: 700px) {
    .link {
        color: purple;
        color: var(--color-link);
    }
}
```
