### ISSUE TITLE
Use variable only from last pseudo-element

### ISSUE THREAD

**Issue by Zmoki** [MadLittleMods/postcss-css-variables#46]
```css
.bar {
  --color: pink;
  color: var(--color);
}

.bar:active {
  --color: blue;
}

.bar:hover {
  --color: red;
}

.bar:focus {
  --color: green;
}
```

Will be transformed to

```css
.bar {
  color: pink;
}

.bar:focus {
  color: green;
}

.bar:hover {
  color: green;
}

.bar:active {
  color: green;
}
```
😞
