### ISSUE TITLE
You readme say you support @media definition, but it's looks like you don't

### ISSUE THREAD

**Issue by MoOx** [MadLittleMods/postcss-css-variables#5]
Input

```css
:root { --fontSize: 2em; }
.Section { font-size: var(--fontSize); }

@media (min-width: 64em) {
  :root { --font-size: 3em; }
}
```

Output

```css
.Section { font-size: 2em; }
```

This is totally unexpected. I expect in a way, to have a font-size corresponding to the definition in the media query.
