### ISSUE TITLE
Feature request: Support for context

### ISSUE THREAD

**Issue by hagenburger** [MadLittleMods/postcss-css-variables#54]
Thanks a lot for your project and the work you put into it. This is very useful!

Do you plan to support context for variables in a way similar how media queries and hover effects work?

### Existing functionality:

``` css
/* Works well: */

:root {
  --color: blue;
}

a {
  color: var(--color);
}
/* =>
  a {
    color: blue;
  }
*/

a:hover {
  --color: green;
}
/* =>
  a:hover {
    color: green;
  }
*/
```

### New functionality:

``` css
/* Not supported: */

:root {
  --color: blue;
}

a {
  color: var(--color);
}
/* =>
  a {
    color: blue;
  }
*/

.my-theme {
  --color: red;
}
/* =>
  .my-theme a {
    color: red;
  }
*/
```
