### ISSUE TITLE
Comma separated rule not expanded into multiple with different values

### ISSUE THREAD

**Issue by MadLittleMods** [MadLittleMods/postcss-css-variables#55]
Input

```css
:root {
  --color: blue;
}

.my-theme {
  --color: red;
}

:root,
.my-theme {
  a {
     color: var(--color);
  }
}
```

Output:
```css
:root,
.my-theme {
  a {
     color: red;
  }
}
```

Expected:
```css
:root {
  a {
     color: red;
  }
}

.my-theme {
  a {
     color: red;
  }
}
```
