### ISSUE TITLE
Comma separated rules are unnecessarily expanded

### ISSUE THREAD

**Issue by amustill** [MadLittleMods/postcss-css-variables#58]
It appears that comma-separated rules are expanded even if the variable value is the same, creating additional unnecessary rules.

Input:
```css
:root {
    --font-family: sans-serif;
}

h1, h2, h3, h4, h5, h6 {
    font-family: var(--font-family);
}
```

Expected output:
```css
h1, h2, h3, h4, h5, h6 {
    font-family: sans-serif;
}
```

Actual output:
```css
h1 {
    font-family: sans-serif;
}

h2 {
    font-family: sans-serif;
}

h3 {
    font-family: sans-serif;
}

h4 {
    font-family: sans-serif;
}

h5 {
    font-family: sans-serif;
}

h6 {
    font-family: sans-serif;
}
```
