### ISSUE TITLE
Error with variables declared within a function

### ISSUE THREAD

**Issue by cmauduit** [MadLittleMods/postcss-css-variables#62]
Hello,

I try to transform a css file (material-components-web.css) that contains variables declared in differents ways. 
Some of them are not replaced by the plugin. For example :
`background-color: color(var(--mdc-theme-text-primary-on-primary, white));`
gives : 
`background-color: color(white;`
So it miss a ')' before ';'

I had a look to the code of the plugin and I think that I found a solution. In the file resolve-value.js, I modified the regex variable : 
    `RE_VAR_FUNC = (/var\((--[^,\s]+?)(?:\s*,\s*(.+))?\)/)`  
to 
    `RE_VAR_FUNC = (/var\((--[^,\s]+?)(?:\s*,\s*([^\)\(]+|(.+)))?\)/);`

It seems to work. If it is ok for you, can you implement it in your future versions?
Thx

**Comment by MadLittleMods** [comment]
Hey @cmauduit,

I just tested this out and I am not getting the same results. Could another plugin be interfering here?

I also added a test to the codebase to make sure this test case is covered, https://github.com/MadLittleMods/postcss-css-variables/commit/dfb5ec10543cbd9e201280f176483ca018145f49

Input:

```css
.box-foo {
	background-color: color(var(--some-color, white));
}
```

Output:

```css
.box-foo {
	background-color: color(white);
}
```

**Comment by kenbellows** [comment]
@MadLittleMods I see this as well in the PostCSS Playground. I'm running Chrome 62 on Windows 7, in case that makes any difference. Screenshot attached.
![postcss-varsinfunctions-bug](https://user-images.githubusercontent.com/657118/32730373-e0493edc-c854-11e7-8455-12a463aae33c.PNG)

**Comment by MadLittleMods** [comment]
Thanks @kenbellows, it looks like the key is to actually have the variable defined which I assumed wasn't because OP had the output value as the fallback value.

Input,

```css
:root {
	--some-color: #f00;
}

.box-foo {
	background-color: color(var(--some-color, white));
}
```

Output:

```css
.box-foo {
	background-color: color(#f00;
}
```
