### ISSUE TITLE
CSS variable declarations in media queries produce duplicate nested output

### ISSUE THREAD

**Issue by jhildenbiddle** [MadLittleMods/postcss-css-variables#64]
Input:

```css
@media screen and (min-width: 480px) {
    :root {
        --color: blue;
    }
    
    body {
        background: var(--color);
    }
}
```

Expected:

```css
@media screen and (min-width: 480px) {
    body {
        background: blue;
    }
}
```

Actual output:

```css
@media screen and (min-width: 480px) {
    
    body {
        background: blue;
    }
    
    @media screen and (min-width: 480px) {
    
        body {
        background: blue;
        }
    }
}
```

Reproducible using [postcss-css-variables Playground](https://madlittlemods.github.io/postcss-css-variables/playground/).
