### ISSUE TITLE
Chaining variables in media queries results in duplicated blocks

### ISSUE THREAD

**Issue by deioo** [MadLittleMods/postcss-css-variables#67]
The issue can be replicated in the [playground](https://github.com/MadLittleMods/postcss-css-variables/issues/64) with the following input:

```css
:root {
  --space-small: 10px;
  --space-large: 20px;
}

@media (min-width: 768px) {
  :root {
    --space-small: 20px;
    --space-large: 30px;
  }
}

h1 {
  padding: var(--space-small) var(--space-large);
}

h2 {
  padding: var(--space-small);
}
```

In the output, the `h2` is defined as expected, while `h1`'s media query block gets duplicated a few times:

```css
h1 {
  padding: 10px 20px;
}

@media (min-width: 768px) {

  h1 {
  padding: 20px 30px;
  }
}

@media (min-width: 768px) {

  h1 {
  padding: 20px 30px;
  }
}

@media (min-width: 768px) {

  h1 {
  padding: 20px 30px;
  }
}

@media (min-width: 768px) {

  h1 {
  padding: 20px 30px;
  }
}
```

If using 3 values for padding, the replication is increased.

The issue might seem related to https://github.com/MadLittleMods/postcss-css-variables/issues/64, the difference being that there is no problem with nesting in the above.
