### ISSUE TITLE
Support for child combinator

### ISSUE THREAD

**Issue by bangseongbeom** [MadLittleMods/postcss-css-variables#7]
Current version supports only [Descendant combinator](http://www.w3.org/TR/css3-selectors/#descendant-combinators)`(.sel1 .sel2)`.
[Child combinator](http://www.w3.org/TR/css3-selectors/#child-combinators)`(.sel1 > .sel2)` should be also supported. 

Input:
```css
.a {
    --color: red;
}

.a > .b {
    color: var(--color);
}
```

Output:
```css
.a > .b {
    color: undefined;
}
```

Expectation:
```css
.a > .b {
    color: red;
}
```
