### ISSUE TITLE
var computed as undefined 

### ISSUE THREAD

**Issue by tomkel** [MadLittleMods/postcss-css-variables#71]
I have a main.css that looks like

```
@import './variables.css'
@import './other.css'
```
variables.css
```
:root {
  --some-var: 0;
}
```
other.css
```
.select {
  width: var(--some-var);
}
```

And the output looks like
```
.select {
  width: undefined;
}
```

**Comment by MadLittleMods** [comment]
@tomkel Please post your full PostCSS setup and plugin order.

You probably need to run `postcss-import` before `postcss-css-variables`.

**Comment by tomkel** [comment]
OK, so I narrowed down the bug a little more. It's not really due to `@import`, but may be a design decision of this library. The bug happens when a selector has a var statement that is not connected to the var definition in any way. like so:
```css
.selector1 {
  --my-var: 0;
}

.selector2 {
  height: var(--my-var);
}
```
In this case, the var statement is computed as `undefined`.

**Comment by MadLittleMods** [comment]
@tomkel That output is as expected. `postcss-css-variables` has no knowledge of the DOM and only statically compiles out selectors that match.

**Comment by cmnstmntmn** [comment]
@MadLittleMods how can this be solved?

**Comment by MadLittleMods** [comment]
@cmnstmntmn There is no solution given the [example here](https://github.com/MadLittleMods/postcss-css-variables/issues/71#issuecomment-375116985). The plugin is behaving as expected.

If you want the variable to flow, you need to be explicit with the relationship. Please create a separate issue if you still have questions.

```css
.selector1 {
  --my-var: 0;
}

.selector1 .selector2 {
  height: var(--my-var);
}
```
