### ISSUE TITLE
Edge case nesting causing no substitution

### ISSUE THREAD

**Issue by satazor** [MadLittleMods/postcss-css-variables#76]
Hello,

I've found an edge case where variables are not being substituted. The above code uses `postcss-nesting` which is set to run before the `postcss-css-variables`.

```css
.discussion-fab {
    background-color: var(--color-white);
    
    &::after {
        content: "";
        box-shadow: inset 0 0 0 0 var(--color-white);
    }

    &.active,
    &:focus {
        background-color: var(--color-science-blue);

        &:hover::after {
            /* This doesn't get substituted! */
            box-shadow: inset 0 0 0 0 var(--color-white);
        }
    }
}
```

The above works but the `:focus` and `.active` had to be duplicated:

```css
.discussion-fab {
    background-color: var(--color-white);

    &::after {
        content: "";
        box-shadow: inset 0 0 0 0 var(--color-white);
    }

    &.active {
        background-color: var(--color-science-blue);

        &:hover::after {
            box-shadow: inset 0 0 0 0 var(--color-white);
        }
    }

    &:focus {
        background-color: var(--color-science-blue);

        &:hover::after {
            box-shadow: inset 0 0 0 0 var(--color-white);
        }
    }
}
```

I'm unsure how to create a test case. The nesting fixtures don't resemble `postcss-nesting` syntax.
