### ISSUE TITLE
Cascading vars: Plugin works correctly? Or browsers do not work correctly?

### ISSUE THREAD

**Issue by belozer** [MadLittleMods/postcss-css-variables#78]
I'am not found specs with examples abount cascading vars. But try this case https://github.com/MadLittleMods/postcss-css-variables#caveats native in Browser on [CodePen](https://codepen.io/belozer/pen/ajwNjv). (without plugin)

```html
<div class="component">
    Black

    <h1 class="title">
        Blue

        <p class="decoration">
            Green

            <h1 class="title">Blue with this plugin, but green per spec</h1>
        </p>
    </h1>
</div>
```

```css
.component {
  --text-color: blue;
}

.component .title {
  color: var(--text-color);
}

.component .decoration {
  --text-color: green;
  color: var(--text-color);
}
```
![image](https://user-images.githubusercontent.com/1655916/43168836-589aeb6e-8fa7-11e8-9ff9-05cdcd05081a.png)
=====

It turns out that the plugin works correctly? Or browsers do not work correctly?

**Comment by belozer** [comment]
Or is this an incorrect example?

And need next
```html
<div class='block theme'>
  Blue
  <h1 class='block__title'>
    Red in plugin, but blue in spec
  </h1>
</div>
```

```css
:root { --color: red }

.theme { --color: blue }

.block, 
.block__title {
  color: var(--color)
}
```

**Comment by MadLittleMods** [comment]
Thanks for noticing. I think it is an incorrect example, https://github.com/MadLittleMods/postcss-css-variables/blob/a817fb90a23eb9dbf7b3848583b67e0299250c3e/README.md#caveats and perhaps had falsely assumed custom properties were inherited. The `--text-color: green;` only applies to `.decoration`.

Your second example, https://github.com/MadLittleMods/postcss-css-variables/issues/78#issuecomment-407575063 compiles as expected (all red btw) because we only take into account explicit relationships.

---

We can simplify the example to the following (feel free to create a PR)

```html
<div class="block theme-blue">
  Red in plugin, but blue in spec
</div>
```

```
:root { --color: red }
.theme-blue { --color: blue }

.block {
  color: var(--color);
}
```

**Comment by belozer** [comment]
@MadLittleMods PR Ready :) https://github.com/MadLittleMods/postcss-css-variables/pull/79

**Comment by MadLittleMods** [comment]
Thanks for the PR @belozer. From my extra digging, I think we just need to change everything to `<div>`.

✔️ I looked some more info to verify and CSS custom properties do inherit, https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables#Inheritance_of_CSS_Variables

:x: The problem with the example is the nesting of `<p>` and `<h1>`. `<p>` can't contain other block-level elements.

 - https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
 - https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements

---

We can update the example to be the following,

```html
<div class="component">
    Black

    <div class="title">
        Blue

        <div class="decoration">
            Green

            <div class="title">Blue with this plugin, but green per spec</div>
        </div>
    </div>
</div>
```

```css
.component {
  --text-color: blue;
}

.component .title {
  color: var(--text-color);
}

.component .decoration {
  --text-color: green;
  color: var(--text-color);
}
```
