### ISSUE TITLE
margin shorthand with 3 values is merged into one

### ISSUE THREAD

**Issue by renestalder** [MadLittleMods/postcss-css-variables#82]
**Input:**

```css
.klt-p-block-heading {
    margin: var(--klt-l-spacing-1, 0) 0 var(--klt-l-spacing-3, 0);
    position: relative;
}
```

**Expected output:**

```css
.klt-p-block-heading {
    margin: 40px 0 30px;
    position: relative;
}
```

**Given output:**

```css
.klt-p-block-heading {
    margin: 40px;
    position: relative;
}
```

Works fine when using margin with 4 values and two values. But not with 3 values. Possible to happen with other shorthands too.
