### ISSUE TITLE
Priority of js defined variables over css defined variables

### ISSUE THREAD

**Issue by 2beers** [MadLittleMods/postcss-css-variables#86]
Is there an option that will enable priority for js defined variables over css ones?
For example in this css
```css
:root {
    --first-color: red;
}
#box {
    background-color: var(--first-color);
}
```

```js
cssvariables({
    variables: {
        "--first-color": "green"
    }
})
```

will output `#box{background-color:red}` and I expected to change the color to green as provided from js options

Thanks
