### ISSUE TITLE
Add option to generate descendant selector rules for rules that use a variable that has been redefined

### ISSUE THREAD

**Issue by brmc** [MadLittleMods/postcss-css-variables#88]
I know that it's impossible to predict DOM-structure, but I believe I have a valid use-case

My company has adopted a combination of the [BEM methodology](http://getbem.com/), which encourages using no descendant selectors (or at the very worst, single-level descendants), and [SMACSS](https://smacss.com/). In doing so we've separated non-functional styles into so-called "thematic contexts" (or maybe "thematic zones?") where we redefine context-sensitive css properties (it behaves in a manner similar to a dependency-injection framework). 

Because of the shallow nesting and lack of side-effects, it would be helpful if simple descendant selectors rules could be generated when usages of rules that have been overwritten have been detect in order to further mimic native behavior

For example here is what a test file with expectations might look like:

```css
/* test-bem-rules.css */
:root {
    --border-color: black;
    --color: black;
}

.t-foo {
    --border-color: grey;
}

.t-bar {
    --color: red;
}

.t-baz {
    border-color: var(--border-color);
    color: var(--color);
}

/* test-bem-rules.expected.css */
.t-baz {
    border-color: black;
    color: black;
}

.t-foo .t-baz {
    border-color: grey;
}

.t-bar .t-baz {
    color: red;
}
```

I understand that this might be too specific of a use case and thus fragile and unreliable for many users, but what are you thoughts on this?

I have a naive prototype for the most basic use case, but I haven't tried anything even remotely complex. If you do not think this feature belongs in this project, would you mind pointing out some gotchas and edge-cases i should be aware of if you have the time?

Thanks

(Also, kudos on such a clean and clear code base. It was very easy to read through, which is especially rare in the JS community in my experience)

**Comment by MadLittleMods** [comment]
@brmc I think this could better work as a separate project, perhaps `postcss-bem-nester` that would create the explicit descendant selector relationships before `postcss-css-variables`.

Example of `postcss-bem-nester` output,
```css
/* test-bem-rules.css */
:root {
    --border-color: black;
    --color: black;
}

.t-foo {
    --border-color: grey;
}

.t-bar {
    --color: red;
}

.t-baz,
.t-foo .t-baz,
.t-bar .t-baz {
    border-color: var(--border-color);
    color: var(--color);
}
```

I didn't think through the edge-cases.

Appreciate the praise ❤️. There is a stale major refactor because I think it could be much much improved, https://github.com/MadLittleMods/postcss-css-variables/tree/major-refactor

**Comment by brmc** [comment]
@MadLittleMods, thanks for the response

By edge cases, i just meant particular hiccups for certain types of rules/selectors or obscure syntax that you ran into along the way, but after running my fork on our css, it seems to work without any immediate glaring problems

Regarding the refactoring, what exactly are you not happy about? 

I mean, it certainly has its own feel and doesn't conform to a particular set of standards, but that's not necessarily a bad thing. the thing that stood out the most and the most important thing is how easy it was to understand. I read through it once and got it. I can imagine the procedural style might make it more difficult to extend, but if you do refactor it, i hope you preserve the clarity and straight-forwardness (and don't over-engineer it for the sake of design patterns :D)

if you want a fresh perspective, feel free to bounce ideas off me

**Comment by MadLittleMods** [comment]
@brmc I find it hard to [fix bugs](https://github.com/MadLittleMods/postcss-css-variables/issues?q=is%3Aissue+is%3Aopen+label%3Abug) because the resolution is brittle(try to understand [`resolve-decl.js`](https://github.com/MadLittleMods/postcss-css-variables/blob/f44aee055c3a7ac122a9dd48b925468dc8786861/lib/resolve-decl.js) or [`resolve-value.js`](https://github.com/MadLittleMods/postcss-css-variables/blob/f44aee055c3a7ac122a9dd48b925468dc8786861/lib/resolve-value.js)). I also think the code to figure out whether a given selector is under the scope of another should be in it's [own module with proper parsing and tests (currently private)](https://github.com/MadLittleMods/postcss-selector-scope-utility)

**Comment by brmc** [comment]
I guess I got lucky. I didn't have to try to look at the details of `resolveDecl`. I operated on the assumption that it worked as expected and just dumped stuff into it and got what I hoped for ;-)

I can take a look later when I get of work

**Comment by MadLittleMods** [comment]
Closing the issue as the discussion has led elsewhere. But I guess we can continue discussing anyway 🤷‍♀️

**Comment by brmc** [comment]
If you want to take it further, you could create an official refactoring issue to discuss such things

**Comment by dotnetCarpenter** [comment]
I just got bitten by this.

Source:
```css
/* BEM http://getbem.com/naming/
Block
	some-icons
Element
	some-icons__icons
*/

.some-icons {
	--size: 2.2em;
	--font-size: 1.1em;
	--border-width: 1px;
	--border-color: var(--color-text);
	--speed: .2s;

	display: flex;
	align-items: center;
	justify-content: space-between;

	font-size: var(--font-size);
}

/* KLUDGE: magix fix so icons does not get squezed on mobile */
@media screen and (max-width: 460px) {
	.some-icons {
		--font-size: 4vw;
	}
}


.some-icons__icons {
	display: flex;
	align-items: center;
	justify-content: center;
	position: relative;

	width: var(--size);
	height: var(--size);

	border: var(--border-width) solid var(--border-color);
	border-radius: 50%;

	transition: border-top-color var(--speed) linear 0s, border-right-color var(--speed) linear 0.1s,
							border-bottom-color var(--speed) linear 0.2s,
							border-left-color var(--speed) linear 0.3s;
	overflow: visible;
}

.some-icons__icons:hover,
.some-icons__icons:focus {
	border-color: var(--color-light);

	text-decoration: none;
}

.some-icons__icons::before {
	position: absolute;
	display: block;

	top: calc(var(--border-width) * -1);
	left: calc(var(--border-width) * -1);

	width: var(--size);
	height: var(--size);

	border: var(--border-width) dashed var(--border-color);
	border-radius: 50%;

	content: '';
}
.some-icons__icons::before:hover,
.some-icons__icons::before:focus {
	border-color: var(--color-light);
}
```

Output:
```css
/* BEM http://getbem.com/naming/
Block
	some-icons
Element
	some-icons__icons
*/

.some-icons {

	display: flex;
	align-items: center;
	justify-content: space-between;

	font-size: 1.1em;
}

@media screen and (max-width: 460px) {

  .some-icons {

	font-size: 4vw;
  }
}

/* KLUDGE: magix fix so icons does not get squezed on mobile */

.some-icons__icons {
	display: flex;
	align-items: center;
	justify-content: center;
	position: relative;

	width: undefined;
	height: undefined;

	border: undefined;
	border-radius: 50%;

	transition: undefined;
	overflow: visible;
}

.some-icons__icons:hover {
	border-color: hsl(26, 100%, 99%);

	text-decoration: none;
}

.some-icons__icons:focus {
	border-color: hsl(26, 100%, 99%);

	text-decoration: none;
}

.some-icons__icons::before {
	position: absolute;
	display: block;

	top: undefined;
	left: undefined;

	width: undefined;
	height: undefined;

	border: undefined;
	border-radius: 50%;

	content: '';
}

.some-icons__icons::before:hover {
	border-color: hsl(26, 100%, 99%);
}

.some-icons__icons::before:focus {
	border-color: hsl(26, 100%, 99%);
}
```

It's the same all over my project.

**Comment by dotnetCarpenter** [comment]
Wow - there is a lot of tools at https://en.bem.info/toolbox/sdk/bem-bemjson-to-decl/ but none of them work with PostCSS out of the box.

**Comment by dotnetCarpenter** [comment]
I got one file that I struggle to get refactor so the postcss-css-variables can deal with it.

Source:

```css
@media (min-aspect-ratio: 1/2) {
	:root {
		--hero-pos-y-start: 0%;
		--hero-pos-y-end: 63%;
	}
}
@media (max-aspect-ratio: 1/2) {
	:root {
		--hero-pos-y-start: 0%;
		--hero-pos-y-end: 100%;
	}
}

.hero {
	height: 50vh;
	margin-bottom: var(--margin-vertical);

	border-bottom: 1px black solid;

	overflow: hidden;
}

.hero--animate img,
.hero--animate source {
	animation: 6s ease-in-out 1s 1 normal forwards burns;
}

.hero__image {
	display: flex;
	width: 100%;
	height: 100%;
}

.hero__image img,
.hero__image source {
	max-width: 100%;
	flex: 1 1 auto;
	object-position: center var(--hero-pos-y-start, 0%);
	object-fit: cover;

	will-change: object-position;
}

@keyframes burns {
	to {
		object-position: center var(--hero-pos-y-end, 100%);
	}
}
```

Output:
```css
.hero {
	height: 50vh;
	margin-bottom: .83rem;

	border-bottom: 1px black solid;

	overflow: hidden;
}

@media screen and (min-width: 768px) {

  .hero {
	margin-bottom: 2rem;
  }
}

.hero--animate img,
.hero--animate source {
	animation: 6s ease-in-out 1s 1 normal forwards burns;
}

.hero__image {
	display: flex;
	width: 100%;
	height: 100%;
}

.hero__image img {
	max-width: 100%;
	flex: 1 1 auto;
	object-position: center 0%;
	object-fit: cover;

	will-change: object-position;
}

@media (max-aspect-ratio: 1/2) {

  .hero__image img {
	object-position: center 0%;
  }
}

@media (min-aspect-ratio: 1/2) {

  .hero__image img {
	object-position: center 0%;
  }
}

.hero__image source {
	max-width: 100%;
	flex: 1 1 auto;
	object-position: center 0%;
	object-fit: cover;

	will-change: object-position;
}

@media (max-aspect-ratio: 1/2) {

  .hero__image source {
	object-position: center 0%;
  }
}

@media (min-aspect-ratio: 1/2) {

  .hero__image source {
	object-position: center 0%;
  }
}

@keyframes burns {
	to {
		object-position: center 100%;
	}
	@media (max-aspect-ratio: 1/2) {

    to {
		object-position: center 100%;
    }
  }
	@media (min-aspect-ratio: 1/2) {

    to {
		object-position: center 63%;
    }
  }
}
```

I am not sure that the `@keyframes` section even is valid CSS...
