### ISSUE TITLE
Optionally preserve

### ISSUE THREAD

**Issue by ar53n** [MadLittleMods/postcss-css-variables#94]
My idea is add option for exclude for some variables. Because i have `postcss-color-function` plugin and i don't preserve only all these variables.

For example i don't want preserve variables with color function.
```css
.box {
    color: color(var(--red) a(90));
    padding-left: var(--pl);
}
```
Result:
```css
.box {
    background: rgba(255, 0, 0, 0.9);
    padding-left: 20px;
    padding-left: var(--pl);
}
```

**Comment by MadLittleMods** [comment]
Currently, if it is an invalid declaration, it will just fallback and work as expected.

 - Is the goal to reduce the resultant size of your CSS?
 - Does `postcss-color-function` choke and throw an error with `color: color(var(--red) a(90));`? Can you ignore those errors?
 - Any ideas on how this option would be configured?


Input: 
```css
:root {
	--red: #f00;
	--pl: 15px;
}

.box {
    color: color(var(--red) a(90));
    padding-left: var(--pl);
}
```

Current output running just `postcss-css-variables`  with `options.preserve = true`

```css
:root {
	--red: #f00;
	--pl: 15px;
}

.box {
    color: color(#f00 a(90));
    color: color(var(--red) a(90));
    padding-left: 15px;
    padding-left: var(--pl);
}
```
